### ISSUE TITLE
PMP crash on load Windows 8.1 [6.3.9600] arch x86_64

### ISSUE THREAD

**Issue by dlerche** [plexinc/plex-media-player#148]
Platform and OS version: Windows 8.1 [6.3.9600] arch x86_64

Plex Media Player app version: Plex Media Player version: 1.0.2.70-15a01542

Brief description of the issue or bug
After install and opening the first time, it shuts down right away.

Steps to reproduce (these will make it easier for development to track down)
Install and launch on Surface Pro 2 running windows 8.1 using external 24" Philips monitor.

Last lines from the log before it crashes or shuts down...
2015-11-13 12:38:17 [ WARN  ] HelperLauncher.cpp @ 83 - Running helper does not match our current version. Killing it and starting a new one. 
2015-11-13 12:38:17 [ DEBUG ] HelperLauncher.cpp @ 64 - Waiting for helper to die 
2015-11-13 12:38:18 [ DEBUG ] HelperLauncher.cpp @ 105 - Disconnected from helper, trying to relaunch 
2015-11-13 12:38:18 [ DEBUG ] HelperLauncher.cpp @ 49 - Connecting to helper 
2015-11-13 12:38:18 [ DEBUG ] HelperLauncher.cpp @ 95 - Failed to connect to helper: "QLocalSocket::connectToServer: Invalid name" 
2015-11-13 12:38:18 [ DEBUG ] HelperLauncher.cpp @ 141 - Launching helper: "C:/Program Files/PlexMediaPlayer/PMPHelper.exe"

**Comment by wm4** [comment]
Did you run an earlier version of PMP on this hardware?

**Comment by dlerche** [comment]
Yes, with same problem, just removed it and reinstalled lastest version. I did just spot the reference to wrong version and did a restart.
I just grepped the latest warn lines from the log
2015-11-13 13:19:28 [ WARN  ] DisplayComponent.cpp @ 239 - Unable to locate current display.
2015-11-13 13:19:28 [ WARN  ] DisplayComponent.cpp @ 239 - Unable to locate current display.
2015-11-13 13:19:28 [ WARN  ] SettingsSection.cpp @ 69 - Looking for value: "clientID" in section: "webclient" but it can't be found
2015-11-13 13:19:28 [ WARN  ] SettingsSection.cpp @ 69 - Looking for value: "fakefullscreen" in section: "main" but it can't be found
2015-11-13 13:19:28 [ WARN  ] PlayerComponent.cpp @ 405 - cplayer: Option af-del: item label @ac3 not found.

**Comment by wm4** [comment]
Find the process PMPHelper.exe, and kill it. Then try to restart Plex Media Player, and upload the resulting plex media player and helper logs. Also try with the DirectX/Angle version.

I'm not sure what could cause this yet.

**Comment by dlerche** [comment]
Done, here are latest logs

Can you specify what you mean by 
"Also try with the DirectX/Angle version."

**Comment by wm4** [comment]
There's a ``Plex Media Player (DirectX)`` start menu entry, and also a ``PlexMediaPlayer-angle.bat`` file in the program dir.

**Comment by wm4** [comment]
(They're both the same.)

**Comment by dlerche** [comment]
Okay, just tried to launch the PlexMediaPlayer-angle.bat
Attached the log and here is the helper log

2015-11-13 13:48:06 [ DEBUG ] HelperSocket.cpp @ 28 - Server connected. 
2015-11-13 13:48:08 [ DEBUG ] CrashUploader.cpp @ 159 - Scanning: "C:/Users/David/AppData/Local/cache/PlexMediaPlayer/crashdumps/incoming" for crashdumps. 
2015-11-13 13:48:08 [ DEBUG ] CrashUploader.cpp @ 169 - Scanning: "C:/Users/David/AppData/Local/cache/PlexMediaPlayer/crashdumps/incoming/1.0.1-56cc6ef9" 
2015-11-13 13:48:08 [ DEBUG ] CrashUploader.cpp @ 169 - Scanning: "C:/Users/David/AppData/Local/cache/PlexMediaPlayer/crashdumps/incoming/1.0.2-15a01542" 
2015-11-13 13:48:08 [ DEBUG ] CrashUploader.cpp @ 70 - Crashdump: "C:/Users/David/AppData/Local/cache/PlexMediaPlayer/crashdumps/processing/1.0.2-15a01542/9fbbc5cd-3d12-48dd-83d8-d945477ae1e0.dmp" 
2015-11-13 13:48:08 [ INFO  ] CrashUploader.cpp @ 80 - Uploading crashdump: "C:/Users/David/AppData/Local/cache/PlexMediaPlayer/crashdumps/processing/1.0.2-15a01542/9fbbc5cd-3d12-48dd-83d8-d945477ae1e0.dmp" 
2015-11-13 13:48:09 [ INFO  ] CrashUploader.cpp @ 133 - Submitted crash report with uuid: "9fbbc5cd-3d12-48dd-83d8-d945477ae1e0"

**Comment by wm4** [comment]
Still don't know what this is caused by.

For the record, it crashes deep within Qt/chromium. Internal crash report: https://app.getsentry.com/plex/plex-media-player/group/89299391/

**Comment by jturcotte** [comment]
Not seeing the log it would seem that [SetFileCompletionNotificationModes](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365538(v=vs.85).aspx) returns false. The only thing that I could find around that could cause it to fail is this article: https://support.microsoft.com/en-us/kb/2568167

@dlerche Is it possible that you have some spyware or adware program installed on that machine that could cause that call to fail in Chromium? If yes, could you try uninstalling them, restarting Windows and try PMP again?

**Comment by dlerche** [comment]
<quote>@dlerche Is it possible that you have some spyware or adware program installed on that machine that could cause that call to fail in Chromium? If yes, could you try uninstalling them, restarting Windows and try PMP again?</quote>
Yes, i suspected the antispyware(s) to be the issue, i will try to uninstall them, and see if that changes anything.

**Comment by dlerche** [comment]
I have now been through uninstalling every possible software that could cause the issue...
Nothing has changed from my point of view, here is my latest crash dump
<pre>
2015-11-13 19:19:40 [ DEBUG ] HelperSocket.cpp @ 28 - Server connected. 
2015-11-13 19:19:42 [ DEBUG ] CrashUploader.cpp @ 159 - Scanning: "C:/Users/David/AppData/Local/cache/PlexMediaPlayer/crashdumps/incoming" for crashdumps. 
2015-11-13 19:19:42 [ DEBUG ] CrashUploader.cpp @ 169 - Scanning: "C:/Users/David/AppData/Local/cache/PlexMediaPlayer/crashdumps/incoming/1.0.1-56cc6ef9" 
2015-11-13 19:19:42 [ DEBUG ] CrashUploader.cpp @ 169 - Scanning: "C:/Users/David/AppData/Local/cache/PlexMediaPlayer/crashdumps/incoming/1.0.2-15a01542" 
2015-11-13 19:19:42 [ DEBUG ] CrashUploader.cpp @ 70 - Crashdump: "C:/Users/David/AppData/Local/cache/PlexMediaPlayer/crashdumps/processing/1.0.2-15a01542/197dd88e-c04c-4b48-9684-0dfdd2e344ea.dmp" 
2015-11-13 19:19:42 [ INFO  ] CrashUploader.cpp @ 80 - Uploading crashdump: "C:/Users/David/AppData/Local/cache/PlexMediaPlayer/crashdumps/processing/1.0.2-15a01542/197dd88e-c04c-4b48-9684-0dfdd2e344ea.dmp" 
2015-11-13 19:19:52 [ INFO  ] CrashUploader.cpp @ 133 - Submitted crash report with uuid: "197dd88e-c04c-4b48-9684-0dfdd2e344ea" 
</pre>

**Comment by dlerche** [comment]
Hi, just updated to windows 10 and now the problem is gone...
