### ISSUE TITLE
Major issues with intel graphics chips and display mode switching

### ISSUE THREAD

**Issue by Zoratt** [plexinc/plex-media-player#677]
A link to information from quite a few users. https://forums.plex.tv/discussion/294977/problem-with-display-mode-switching

When you watch a video that the gpu tries to change to 24fps, the screen blacks out and everything freezes.

Since the Creators version of Windows 10 was forced on us, everything was working fine.

The Open GL can get us to limp on for a while, but it has continued to be an issue since November of 2017 and new drivers, and updates to PMP haven't addressed the issue.

**Comment by Flippage** [comment]
Same issue here. We have to alt+tab out and back in when we play or exit any video. And if I roll back my windows version, it automatically installs the updates again.

**Comment by tommeh1337** [comment]
I have the exact same problem. PMP + W10 Fall creators update + display mode switching is a no-go.

**Comment by Morfeu78** [comment]
I have the same problem with display switching.  Hardware is a Nuc 54250 + Marantz 5011 + LG 65e6. Software is PMP + W10 Fall Creators Update.

**Comment by Morfeu78** [comment]
P.s.: open glass does not resolve the issue for me.

**Comment by Morfeu78** [comment]
*GL

**Comment by LongChair** [comment]
Yeah the W10 Fall creators update has been breaking ANGLE support it seems.
We discussed that internally to restore OpenGL as default rendering method in next updates.

Until then you can change this to OpenGL, it should fix the issue.

**Comment by Flippage** [comment]
Changed to OpenGL. I also updated my Intel HD graphics drivers to the latest version. openGL seems to have done the trick, and I'm not getting the issues I used to get when running OpenGL. 

Happy camper here. 

Fyi - I did some googling, and I think this is a Windows 10 issue. Probably needs to be bugfixed by Microsoft.

**Comment by adaigre** [comment]
Same problem here since 1709 ...
But I have ATI HD 6XXX (don't remember).
Really annoying.

**Comment by MattyBalaam** [comment]
I have tried updating my drivers and switching on Native OpenGL but this does not fix the issue.

**Comment by LongChair** [comment]
> but the screen resolution does not match the video.

I'm not sure to understand what you mean there, can you be a bit more specific ?
If you mean that AutoFrameRate will not switch to 720p video mode when you're running 1080p video mode, but just switches refresh rate, that is by design. a,d there is not much that can be done about this at the moment.

Thanks for you feedback.

**Comment by adaigre** [comment]
@LongChair Sorry !
When I play a 24FPS video, Plex won't switch my HDMI output to 24 Hz (it stays at 60 Hz). It worked before (before Windows 1709).
Surprisingly it seems to attempt a HDMI video mode change (the screen flashes briefly).
If I don't enable OpenGL Native mode I can't play any videos (mouse is flashing and screen stays black).

Also it would be interresting to switch resolution too in the future. I think my TV handle upscaling better than Plex. But refresh rate is more important at the moment as playing 24 FPS video with 60 Hz refresh rate causes weird things on the video (slow down and accelerate slightly).

**Comment by LongChair** [comment]
@adaigre : 
Just to make sure, did you enable display mode switching in setting ? :)
If so can you please attach a full log file so that i can have a look ?
I don't seem to have that issue on Windows. might be driver related, but logs could eventually help.

**Comment by LongChair** [comment]
@torsaxtorff @MattyBalaam @adaigre : well maybe some logs could help here.
Please provide me some.

**Comment by MattyBalaam** [comment]
Of course. I cleared previous logs

1. Opened App
2. Selected Video
3. Used ctrl-tab workaround to show video
4. stopped video
5. Used ctrl-tab workaround to show interface
6. Closed app.

[PlexMediaPlayer.log](https://github.com/plexinc/plex-media-player/files/1950838/PlexMediaPlayer.log)

I have looked around and it appears that KODI may have the same issue: https://forum.kodi.tv/showthread.php?tid=322761

**Comment by LongChair** [comment]
@MattyBalaam : Ok here is one more idea i had.

In the folder where PMP is installed, you'll find plenty of dlls.
The zip below contains updated versions for 3 of those those.

Can you please check if replacing those would make it any better and let me know ? 
(You might want to backup the other versions before overwrtitting those, in case this turns bad :p )
https://www.dropbox.com/s/6tbwdfdns0prxke/dll.zip?dl=0

If that works, then i might have an idea of where the issue is :)

**Comment by MattyBalaam** [comment]
Yes, that works, nice work.

1. The app starts the buffering animation,
2. Briefly switches to a black screen for about half a second
3. Buffering animation returns
4. Video starts playing.
5. On stop, the interface returns.

**Comment by LongChair** [comment]
Here is a second set of libs, please let me know if they fix it as well :

https://www.dropbox.com/s/m4lt6564o1m3e0r/dll_5.10.zip?dl=0

**Comment by MattyBalaam** [comment]
Very happy to confirm this also works.

**Comment by Zoratt** [comment]
LongChair, Thank you tons! I was about to give you my Log Files, but your fix (I used the 2nd set of libs) has fixed the problem.

I of course then installed the new PMP version, which replaced those files and broke it again, but putting them back in again to 2.9 re-fixed it again for me.

**Comment by LongChair** [comment]
@Zoratt @MattyBalaam : in order for me to make sure we can make the safest patch, would you mind one last check with the libs below 

https://www.dropbox.com/s/xpun75nlmxk7hbq/dll_5.9.5.zip?dl=0

Thanks !

**Comment by Zoratt** [comment]
@LongChair: I just downloaded and installed the dll_5.9.5.zip files and restarted PMP 2.9.

I played a number of different videos with different qualities and they all played correctly.

**Comment by LongChair** [comment]
@Zoratt @MattyBalaam : could you guys check that this build fixes the issue as well ? 
https://www.dropbox.com/s/5et27g9gcs691f3/PlexMediaPlayer-2.10.0.842-38aa88b8-windows-x64.exe?dl=0

I'll PR the change if it does :)
Thanks !

**NOTE** : this build might not be 100% functionnal on other aspects (GUI) it's still Work in progress internally.

**Comment by adaigre** [comment]
@LongChair The second set of libs fix the issue on my ATI ! Thanks a lot !

**Comment by LongChair** [comment]
@adaigre : can you check the build above .. which should be the final fix ? :)

**Comment by MattyBalaam** [comment]
I’ve installed the new build and everything is working here. Great work.

**Comment by Zoratt** [comment]
@LongChair I installed the build and the video is playing correctly too. Thanks again. I think this is going to relieve quite a few people.

Mind if I ask what was causing the issue, and how things had worked until the Windows 10 update? or was that not really related?

**Comment by LongChair** [comment]
Hi guys : in the meantime that build should be the latest with the fix : 

https://www.dropbox.com/s/w7neafa3ymv86mk/PlexMediaPlayer-2.10.0.854-c1633f57-windows-x64.exe?dl=0

Please be patient until the fix is merged :)

**Comment by LongChair** [comment]
PR addressing this issue was merged.
