### ISSUE TITLE
GUI Translation issues

### ISSUE THREAD

**Issue by Ribero** [plexinc/plex-media-player#829]
Issue #782 has been marked closed although not completely fixed. Many fields are left in english (dates, duration...) leaving the GUI in a very mixed situation.

Can you please re-open #782 for easier tracking.

Thanks !

**Comment by mseeley** [comment]
HI @Ribero we're continuing to address translation issues a we find them. It's going to be an ongoing area for improvement.  I closed #782 after we addressed the feedback. These screenshots are from our latest code. They may not be released due to release cadence.

![screen shot 2019-02-13 at 2 38 10 pm](https://user-images.githubusercontent.com/30019/52754083-5beadb80-2f9d-11e9-830b-5659f37ee76b.png)
![screen shot 2019-02-13 at 2 37 55 pm](https://user-images.githubusercontent.com/30019/52754084-5beadb80-2f9d-11e9-8cee-85a03d0073ff.png)
![screen shot 2019-02-13 at 2 36 08 pm](https://user-images.githubusercontent.com/30019/52754085-5beadb80-2f9d-11e9-80ab-63832d189c9a.png)
![screen shot 2019-02-13 at 2 35 41 pm](https://user-images.githubusercontent.com/30019/52754086-5beadb80-2f9d-11e9-8105-f37c0c9336eb.png)
![screen shot 2019-02-13 at 2 34 59 pm](https://user-images.githubusercontent.com/30019/52754087-5c837200-2f9d-11e9-8014-82b710cdf9fa.png)

Sound good?

**Comment by Ribero** [comment]
Hi @mseeley, thanks a lot for the feedback.

We are almost Ok. The first four screen capture are correct.

The last one is still incomplete and incorrect (2 small issues are left):

in red: not translated -> **months** (english) should be translated.  (by **mois** in french)
in green: incorrect translation (it make no sense): the word "**Depuis**" should not be used and should be replaced by "**Il y a**". The filed syntax is not correct:

- 2 ans Depuis -> Il y a 2 ans
- 10 ans Depuis -> Il y a 10 ans
- 3 months Depuis -> Il y a 3 mois

![52754087-5c837200-2f9d-11e9-8014-82b710cdf9fa](https://user-images.githubusercontent.com/2266264/52782629-cfe5bc00-304f-11e9-97e5-6c5978c59e65.png)

The right syntax is: "**Il y a**" + _duration_ (**Il y a** means: **ago**)
should look something like :   `%(duration)s ago` ->  `il y a %(duration)s`

ex:
**Il y a** _2 heures_ <-> _2 hours_ **ago**
**Il y a** _10 minutes_ <-> _10 minutes_ **ago** 

Durations units should be one of these:

- Year(s): an(s)
- Month(s): mois
- Day(s): jour(s)
- Hour(s): heure(s)
- Minute(s): minute(s)
- Second(s): seconde(s)

I hope it's clear. Do not hesitate if you need other explanation.

**Comment by mseeley** [comment]
😬, thanks @Ribero. I found a couple things:

1. `3 months Depuis` is caused by no FR translation for `{months} months`. I wonder how it's slipped through.
1. "Depuis" is caused by the following key/value: `"{unitOfTime} ago": "{unitOfTime} Depuis"`. Although, this looks like a bug as we have another key/value that is correct: `"{timeAgo} ago": "il y a {timeAgo}",`

I'll get the

**Comment by mseeley** [comment]
In addition to the above I fixed a broken FR translation for `{months} months`. It was mistakingly translated to `{mounths} mois`. Here we are running with consolidated/updated translations:

![screen shot 2019-02-15 at 11 58 24 am](https://user-images.githubusercontent.com/30019/52886761-75b12d80-3119-11e9-8625-8b3c4e5deb1e.png)

**Comment by Ribero** [comment]
Perfect. Thank you !

**Comment by mseeley** [comment]
Alrighty, the code and translation changes have been integrated into our app. They'll be included in v3.89.x of the Desktop layout.

**Comment by Ribero** [comment]
Hi @mseeley !
any chance to get the fix in the legacy client ? On macOS (at least) Plex Media Player still does not include the fix.

**Comment by mseeley** [comment]
Hi @Ribero, I'm asking about this.

**Comment by mseeley** [comment]
Hi @Ribero the update has been delayed (obviously 😬). Our web client is bundled with PMP and PMS at the same time. There's some heightened sensitivity to updating the version bundled with PMS. A large change to user settings handling requires more testing before it the web client is ready to be bundled.

I apologize for the inconvenience!

**Comment by Ribero** [comment]
Hi, Any update ? Will this fix land in a release ? Thanks for our feedback

**Comment by mseeley** [comment]
Hi @Ribero good of you to ping. This has been way long coming. @markus101 is going to help out here.

**Comment by markus101** [comment]
The desktop app has been updated in the latest PMP release.

**Comment by Ribero** [comment]
Well, well, well... I'm afraid this version is screwed up in terms of translation. It is huge mix between english and all other languages... Tried in French & Italian... same issue. Even is you switch the language in preferences, many fields (that were correctly translated before) remains in english.

<img width="746" alt="Capture d’écran 2019-05-26 à 21 03 00" src="https://user-images.githubusercontent.com/2266264/58385996-ac8cbe80-7ff9-11e9-8e28-00cee70ef73e.png">

**Comment by OttoKerner** [comment]
This a is a server issue, which is already known.

**Comment by Ribero** [comment]
Ok thanks for the update. Good to know it's already tracked
